// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cluster_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ClusterMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClusterMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cluster_5fmessage_2eproto() {
  protobuf_AddDesc_cluster_5fmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cluster_message.proto");
  GOOGLE_CHECK(file != NULL);
  ClusterMessage_descriptor_ = file->message_type(0);
  static const int ClusterMessage_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClusterMessage, image_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClusterMessage, radius_variance_),
  };
  ClusterMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClusterMessage_descriptor_,
      ClusterMessage::default_instance_,
      ClusterMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClusterMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClusterMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClusterMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cluster_5fmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClusterMessage_descriptor_, &ClusterMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cluster_5fmessage_2eproto() {
  delete ClusterMessage::default_instance_;
  delete ClusterMessage_reflection_;
}

void protobuf_AddDesc_cluster_5fmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025cluster_message.proto\";\n\016ClusterMessag"
    "e\022\020\n\010image_id\030\001 \002(\005\022\027\n\017radius_variance\030\002"
    " \002(\002B\026B\024ClusterMessageProtos", 108);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cluster_message.proto", &protobuf_RegisterTypes);
  ClusterMessage::default_instance_ = new ClusterMessage();
  ClusterMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cluster_5fmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cluster_5fmessage_2eproto {
  StaticDescriptorInitializer_cluster_5fmessage_2eproto() {
    protobuf_AddDesc_cluster_5fmessage_2eproto();
  }
} static_descriptor_initializer_cluster_5fmessage_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int ClusterMessage::kImageIdFieldNumber;
const int ClusterMessage::kRadiusVarianceFieldNumber;
#endif  // !_MSC_VER

ClusterMessage::ClusterMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ClusterMessage::InitAsDefaultInstance() {
}

ClusterMessage::ClusterMessage(const ClusterMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ClusterMessage::SharedCtor() {
  _cached_size_ = 0;
  image_id_ = 0;
  radius_variance_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClusterMessage::~ClusterMessage() {
  SharedDtor();
}

void ClusterMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ClusterMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClusterMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClusterMessage_descriptor_;
}

const ClusterMessage& ClusterMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cluster_5fmessage_2eproto();  return *default_instance_;
}

ClusterMessage* ClusterMessage::default_instance_ = NULL;

ClusterMessage* ClusterMessage::New() const {
  return new ClusterMessage;
}

void ClusterMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    image_id_ = 0;
    radius_variance_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClusterMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 image_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &image_id_)));
          set_has_image_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_radius_variance;
        break;
      }
      
      // required float radius_variance = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_radius_variance:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &radius_variance_)));
          set_has_radius_variance();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ClusterMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 image_id = 1;
  if (has_image_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->image_id(), output);
  }
  
  // required float radius_variance = 2;
  if (has_radius_variance()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->radius_variance(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ClusterMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 image_id = 1;
  if (has_image_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->image_id(), target);
  }
  
  // required float radius_variance = 2;
  if (has_radius_variance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->radius_variance(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ClusterMessage::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 image_id = 1;
    if (has_image_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->image_id());
    }
    
    // required float radius_variance = 2;
    if (has_radius_variance()) {
      total_size += 1 + 4;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClusterMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClusterMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClusterMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClusterMessage::MergeFrom(const ClusterMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_image_id()) {
      set_image_id(from.image_id());
    }
    if (from.has_radius_variance()) {
      set_radius_variance(from.radius_variance());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClusterMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClusterMessage::CopyFrom(const ClusterMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClusterMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void ClusterMessage::Swap(ClusterMessage* other) {
  if (other != this) {
    std::swap(image_id_, other->image_id_);
    std::swap(radius_variance_, other->radius_variance_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClusterMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClusterMessage_descriptor_;
  metadata.reflection = ClusterMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
